### ISSUE TITLE
[bug] embeds don't show

### ISSUE THREAD

**Issue by hyperphysin** [xRyul/link-navigation#14]
![Screenshot 2024-10-19 at 1 39 44 AM](https://github.com/user-attachments/assets/ea067977-2e2e-4d8b-9b83-18687eef1cf5)
![Screenshot 2024-10-19 at 1 40 17 AM](https://github.com/user-attachments/assets/22d80211-3542-4967-a17e-8e11fb774e41)

**Comment by xRyul** [comment]
Thanks! Should be fixed in [0.0.9](https://github.com/xRyul/link-navigation/releases/tag/0.0.9)
